### PR TITLE
Move typeRoots paths relative to gruntfile when inside tsconfig.json

### PR DESCRIPTION
**Pull request by beuted**
Linked issue: https://github.com/TypeStrong/grunt-ts/issues/397

### CODE REVIEW

**Comment by beuted** [comment]
`Error: Invalid testExecute node present on target "issue_397".  Value of testExecute must be a function.`

:/ sry I was not able to test

**Comment by nycdotnet** [comment]
I've figured it out.  I think the trouble you're having is that you've edited the files inside the "internal" folder.  This is the folder where we store the "last known good" version of the compiler, not the latest bits.  Sorry for the confusion.

Please apply any edits you've made to `tasks-internal/modules/interfaces.d.ts` to `tasks/modules/interfaces.d.ts` and so forth.  Now it makes sense why your changes were not appearing!

**Comment by beuted** [comment]
I think I figured things out,
Should I run `grunt release` before submitting PR ?

**Comment by nycdotnet** [comment]
Looks good to me.  Thank you!

**Pull request merged**
