### PR TITLE
Use tsc 1.8.10 and move to peerDependencies

### PR DESCRIPTION
**Pull request by vvakame**
Use tsc 1.8.10 and move to peerDependencies.
Update tsd.json.

I tried `typescript@next` with this change. It can complete `npm run test`.

### CODE REVIEW

**Comment by blakeembrey** [comment]
LGTM. Should be released as a major version since it's breaking TypeScript bundling.

**Comment by vvakame** [comment]
👍 
@nycdotnet ping

**Comment by nycdotnet** [comment]
:-) I am actually working on this right now.  Should be out in the next hour or so.  I am trying to update lodash too.

**Comment by nycdotnet** [comment]
Thanks!

**Comment by nycdotnet** [comment]
This should be available as `grunt-ts@6.0.0-beta.1`.  Please let me know if it works for you.

**Pull request merged**
