### PR TITLE
:memo: noEmitOnError

### PR DESCRIPTION
**Pull request by basarat**
closes https://github.com/TypeStrong/grunt-ts/issues/284

### CODE REVIEW

**Comment by nycdotnet** [comment]
I'm in ur Pull Request merging ur conflicts...

**Comment by basarat** [comment]
> I'm in ur Pull Request merging ur conflicts...

sorry ... can I help?

**Comment by nycdotnet** [comment]
No I was just kidding around. Nevermind.  I get no sleep these days and sometimes I think things are clever and they actually make no sense - haha.

**Comment by basarat** [comment]
:rose: :)

**Pull request merged**
