### PR TITLE
Issue #376 - Pretty JSON output for tsconfig

### PR DESCRIPTION
**Pull request by RyanThomas73**
Submitting this pull request as a WIP while I work on adding additional unit tests.

### CODE REVIEW

**Comment by nycdotnet** [comment]
Generally looks good.

Please use utils.eol for the line feed instead of reading from the os object.  We use whatever the person has set up in Grunt (which is the os default unless they've overridden it).

Do you need help setting up the tests?

**Comment by nycdotnet** [comment]
Looking great. Are you done?

**Comment by RyanThomas73** [comment]
I'm done now unless there is anything you want me to add or adjust.

**Comment by nycdotnet** [comment]
Thanks!  Will pull in ASAP.

**Comment by nycdotnet** [comment]
Sorry this took forever, but I've just merged this in.  Thank you!  Well done.

**Comment by nycdotnet** [comment]
This is released in grunt-ts v6.0.0-beta.16 on npm.  Thank you!

**Pull request merged**
