### PR TITLE
Adding support for Node 6

### PR DESCRIPTION
**Pull request by franleplant**
Hi!
     In the context of https://github.com/TypeStrong/grunt-ts/issues/369 I've created this mini PR with:
- Chokidar updated to latest version (1.6)
- Add node 4,5 and 6 to Travis build

I've run the tests in my local with node 6 and they work and I also tested with the original repo where the issue came up and it also works.

Thanks!
Fran

### CODE REVIEW

**Comment by nycdotnet** [comment]
Thank you.  I will check this out ASAP.

**Comment by arg20** [comment]
@nycdotnet any updates on this?

**Comment by nycdotnet** [comment]
Thanks very much, @franleplant .

**Comment by franleplant** [comment]
Hi @nycdotnet ! Thanks for your work. Just a little comment about this:
- We've been using my fork for a 10 days without problems
- It's good to have good references about this patch working

**Pull request merged**
