### PR TITLE
Exclude files

### LINKED ISSUE #285: Fix tsconfig.json exclude support to support files
Officially, the tsconfig.json exclude property can support file names.  Current implementation in grunt-ts only supports directories.  (https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#exclude-property-support-in-tsconfigjson)

### PR DESCRIPTION
**Pull request by errorx666**
fix #285 (with tests)

### CODE REVIEW

**Comment by nycdotnet** [comment]
Thank you for contributing this!

**Comment by errorx666** [comment]
@nycdotnet While it does work as intended, I notice performance is slower as the filtering happens after the globber has already recursed into the excluded directories.  E.g., `node_modules` can take a while to walk, just to have all of its files excluded in the filter step.

**Comment by nycdotnet** [comment]
Ah - that's what all the horrible code I wrote that you deleted was doing.  :-)

Care to submit a new PR?

**Comment by errorx666** [comment]
Sure, I'll work on a hybrid approach when I get a chance.

**Comment by nycdotnet** [comment]
OK.  If I'm ready to push a new version (in the next week or two) I may work back in the old optimization code if I don't see an update from you.

Thanks again for your contribution!!

**Comment by justinbleach** [comment]
Looking forward to this fix in a release as I am currently seeing the typings duplicate issue using the tsconfig supplied in the angular.io quickstart guide with grunt-ts. Thanks for the fix guys!

**Pull request merged**
